services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: finot-db
      MYSQL_USER: martine
      MYSQL_PASSWORD: martine
      MYSQL_ROOT_PASSWORD: martine
    ports:
      - "3306:3306"
