services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: finot-db
      MYSQL_USER: martine
      MYSQL_PASSWORD: martine
      MYSQL_ROOT_PASSWORD: martine
    ports:
      - "3306:3306"
  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_URL=http://localhost:3333
  ai:
    build:
      context: ./ai
    ports:
      - "8000:8000"