services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/finot-db
      - SPRING_DATASOURCE_USERNAME=martine
      - SPRING_DATASOURCE_PASSWORD=martine
    depends_on:
      - db

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_URL=http://localhost:3333

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: finot-db
      MYSQL_USER: martine
      MYSQL_PASSWORD: martine
      MYSQL_ROOT_PASSWORD: martine
    ports:
      - "3306:3306"
